config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root 'pages#index'
  get 'editor', to: 'pages#editor'
  get 'admin', to: 'pages#admin'

  resources :appointments
  post 'appointments_ajax', to: 'appointments#ajax'

  resources :sessions, only: [:destroy, :new, :create]


end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :orders

  validates :name, presence: true, length: { in: 2..100 }
  validates_email_format_of :email
  validates :email, presence: true, uniqueness: { case_sensitive: false }

  before_save do
    self.email = email.downcase
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :client

  has_attached_file :image,
                    :url => "/images/:client_id/:style/:basename.:extension",
                    :path => ":rails_root/public/images/:client_id/:style/:basename.:extension",
                    :default_url => "/images/:client_id/:style/example_data.csv", # :id - (id orders)
                    styles: { thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates_attachment_size :image, less_than: 1000000

  Paperclip.interpolates :client_id do |attachment, style|
    attachment.instance.client.id
  end

  validates :time, presence: true
  validates :date, presence: true
end

app/models/setting.rb
class Setting < ActiveRecord::Base
  def self.crypt
    ActiveSupport::MessageEncryptor.new('wsdfwer wedf wed wedwe d324rt34t54yg4 grefgerfewf34r3 4r3fewrferf34 34rfewrf')
  end

  before_create do
    if self.typ == 'password'
      key = Setting.crypt
      self.value = key.encrypt_and_sign(self.value)
    end
  end

  def self.decrypt(data)
    key = Setting.crypt
    key.decrypt_and_verify(data)
  end

  def self.find_name(data)
    result = Setting.find_by name: data
    if result
      result.value
    else
      nil
    end
  end

  def self.weekend_days
    weekend_days = Setting.find_name('weekend_days')
    if weekend_days
      unless weekend_days.strip.empty?
        return weekend_days
      end
    end
    return false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper

  private

  def is_number?(el)
    el.to_f.to_s == el.to_s || el.to_i.to_s == el.to_s
  end

  def authenticate_admin_user!
    redirect_to new_session_path unless user_admin?
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  skip_before_action :verify_authenticity_token #for ajax jquery

  def index
    @setting_weekend_days = Setting.weekend_days

    day_off = Setting.find_name('weekend_days_week')
    if day_off
      mas = day_off.split(",")
      @mas_weekend = []
      mas.each do |x|
        @mas_weekend << 0 if x == 'sunday'
        @mas_weekend << 1 if x == 'monday'
        @mas_weekend << 2 if x == 'tuesday'
        @mas_weekend << 3 if x == 'wednesday'
        @mas_weekend << 4 if x == 'thursday'
        @mas_weekend << 5 if x == 'friday'
        @mas_weekend << 6 if x == 'saturday'
      end
    else
      @mas_weekend = [0, 6]
    end

    time_start_work = Setting.find_name('time_start_work')
    time_end_work = Setting.find_name('time_end_work')
    if time_start_work && time_end_work
      @time_start_work = time_start_work.to_i
      @time_end_work = time_end_work.to_i
    else
      @time_start_work = 8
      @time_end_work = 20
    end

    time_step = Setting.find_name('time_step')
    if time_step
      if is_number?(time_step)
        @setting_time_step = time_step
        return
      end
    end
    @setting_time_step = 30
  end

  def ajax
    date = params[:date].to_date
    orders = Order.where(date: date).as_json

    result = {}
    orders.each_with_index do |el, index|
      result[index] = el["time"].strftime("%I:%M %p")
    end

    render json: result
  end

  def create
    #check time and date
    test = Order.new(time: person_params[:time])
    order_exist = Order.find_by(date: person_params[:date], time: test.time)
    if order_exist
      flash[:error] = { error: ["This time is busy"] }
      redirect_to action: "index"
      return
    end

    client = Client.find_by email: person_params[:email]
    unless client
      client_new = Client.new(name: person_params[:name], email: person_params[:email])
      if client_new.save
        client = client_new
      else
        flash[:error] = client_new.errors
        redirect_to action: "index"
        return
      end
    end

    order = Order.new(time: person_params[:time], date: person_params[:date], image: person_params[:image])
    order.client = client
    if order.save
      flash[:message] = "Order added"
      EmailSendJob.perform_later(client, order)
      redirect_to action: "index"
    else
      flash[:error] = order.errors
      redirect_to action: "index"
      return
    end

  end

  private

  def person_params
    params.require(:appointments).permit(:email, :name, :date, :time, :image)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index

  end

  def admin

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render layout: 'application_nil'
  end

  def create
    admin_password = Setting.find_name('admin_password')
    admin_name = Setting.find_name('admin_name')
    if admin_password && admin_name
      admin_password = Setting.decrypt(admin_password)
      admin_name = Setting.decrypt(admin_name)
    else
      redirect_to admin_root_path
      return
    end

    if person_params[:password] == admin_password &&
           person_params[:name] == admin_name
      session[:user_admi] = token_encode
      redirect_to admin_root_path
    else
      redirect_to action: :new
    end
  end

  def destroy
    session.delete(:user_admi)
    reset_session
    redirect_to root_url
  end

  private

  def person_params
    params.require(:sessions).permit(:name, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def solt
    "sdfweweevcrtgthw1qw3Qweecvewvcw432WEewre324teFveghre"
  end

  def user_admin?
    session[:user_admi] == token_encode
  end

  private

  def token_encode
    payload = { key: solt }
    token = JWT.encode payload, solt, 'HS256'

    Base64.strict_encode64(token)
  end

  # tok = Base64.strict_decode64(token)
  # decoded_token = JWT.decode tok, solt, true, { algorithm: 'HS256' }
end

app/views/admin/weekend_days/index.html.erb
<%= stylesheet_link_tag "jquery-ui.multidatespicker.css" %>

<div class="activeadmin-row">
  <div class="activeadmin-col-md-6">
    <div id="mdp-demo"></div>
    <br>
    <div id="weekend_days_save" class="botton-activeadmin">Save</div>
  </div>
  <div class="activeadmin-col-md-6">
    <div id="mdp-result"></div>
  </div>
</div>

<%= javascript_include_tag "jquery-ui.multidatespicker" %>

<%= render partial: "shared/setting_weekend_days" %>

<%= javascript_include_tag "weekend_days" %>

app/views/appointments/index.html.erb
<div>
  <div class="form-group">
    <div class="row">
      <div class="col-md-6">
        <div id="datetimepicker_day"></div>
      </div>
      <div class="col-md-6">
        Busy time:
        <div id="time"></div>
      </div>
    </div>
  </div>

</div>

<%= form_for :appointments, url: {action: "create"}, html: {class: "new_order", multipart: true } do |f| %>
  <div class="form-group">
    <div id="datetimepicker_time"></div>
  </div>
  <div class="form-group">
    <%= f.text_field :name, class: "form-control", placeholder: "name" %>
  </div>
  <div class="form-group">
    <%= f.text_field :email, class: "form-control", placeholder: "email" %>
  </div>
  <div class="form-group">
    <label class="btn btn-default btn-file">
      Browse <%= f.file_field :image, class: "form-control display-none", id: "appointments_file", accept: "image/png,image/gif,image/jpeg,image/bmp" %>
    </label><i class="margin-left-10 valid-file fa" aria-hidden="true"></i>
  </div>
  <div class="form-group">
    <%= f.submit "New order", class: "btn, btn-default", id: "order_submit" %>
  </div>
<% end %>

<%= javascript_tag do %>
  Setting_time_step = <%= @setting_time_step %>;

  Setting_time_work = [];
  for (i = <%= @time_start_work %>; i <= <%= @time_end_work %>; i++) {
  Setting_time_work.push(i);
  }

  Setting_mas_weekend = <%= @mas_weekend %>;

<% end %>
<%= render partial: "shared/setting_weekend_days" %>

<%= javascript_include_tag "appointments" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Starter Template for Bootstrap</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>"><%= Setting.find_name('site_name') %></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="<%= appointments_path %>">Make and Appointment</a></li>
        <li><a href="<%= editor_path %>">Editor</a></li>
        <!--<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
          </ul>
        </li>-->
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>
<div class="container">
  <!--<% flash.each do |name, msg| %>-->
    <!--<% content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>-->
      <!--<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>-->
      <!--<% msg %>-->
      <!--<% end %>-->
    <!--<% end %>-->

  <%= yield %>

  <% if flash[:message] %>
    <%= flash[:message] %>
  <% end %>

  <% if flash[:error] %>
    <ul>
      <% flash[:error].each do |attr, msg| %>
        <% msg.each do |val| %>
          <li><%= attr %>&nbsp;<%= val %></li>
        <% end %>
      <% end %>
    </ul>
  <% end %>
</div>
</body>
</html>

app/views/layouts/application_nil.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Starter Template for Bootstrap</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/pages/admin.html.erb
<%= @user_admin %>

app/views/pages/editor.html.erb
COLLECTION
<a href=""></a>
<br><br>

COLOR FAMILY
<a href=""></a>
<br><br>

FINISH TYPE
<a href=""></a>
<br><br>

SKINTONE
<div id="skintone_range"></div>
<br>
<br><br>

NAIL LENGTH
<div id="nail_length_range"></div>

<%= javascript_include_tag "range" %>

app/views/shared/_setting_weekend_days.html.erb
<%= javascript_tag do %>
  $(document).ready(function() {

  <% if @setting_weekend_days %>
    Setting_w = '<%= @setting_weekend_days %>';
    Setting_weekend_days = [];
    Setting_weekend_days = Setting_w.split(",");
  <% else %>
    Setting_weekend_days = false;
  <% end %>

  });
<% end %>